name: Version Check (.csproj)

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.head_ref == 'development'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from PR branch
        id: pr_version
        run: |
          VERSION_PR=$(grep -oPm1 "(?<=<Version>)[^<]+" "csm_foundation\csm_foundation_core\CSM Foundation Core\CSM Foundation Core\CSM Foundation Core.csproj")
          echo "version_pr=$VERSION_PR" >> $GITHUB_OUTPUT

      - name: Get version from main branch
        id: main_version
        run: |
          git fetch origin main
          VERSION_MAIN=$(git show origin/main:path/to/YourProject.csproj | grep -oPm1 "(?<=<Version>)[^<]+")
          echo "version_main=$VERSION_MAIN" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          echo "PR version: ${{ steps.pr_version.outputs.version_pr }}"
          echo "Main version: ${{ steps.main_version.outputs.version_main }}"
          if [ "${{ steps.pr_version.outputs.version_pr }}" == "${{ steps.main_version.outputs.version_main }}" ]; then
            echo "❌ Version has not been updated!"
            exit 1
          else
            echo "✅ Version updated."
